import type { Guide, Prompt, Gem } from './types';

export const guides: Guide[] = [
  {
    id: "guide_001",
    title: "Research Writing Fundamentals for African Markets",
    slug: "research-writing-fundamentals",
    description: "Learn structured approaches to academic and business research writing tailored to African contexts and audiences.",
    content: "# Full Guide Content in Markdown\n\n## Section 1\n...",
    author: "CRANE JLA Consults",
    category: "Writing",
    readingTime: 12,
    keyTakeaways: ["Understand your audience", "Structure for clarity", "Cite with integrity", "Leverage local data"],
    datePublished: "Dec 2025",
    featured: true,
    order: 1,
    tags: ["research", "writing", "africa"],
  },
  {
    id: "guide_002",
    title: "Data Analysis Frameworks for SME Profitability",
    slug: "data-analysis-frameworks-sme-profitability",
    description: "Practical data analysis approaches for small and medium enterprises looking to optimize profitability and make data-driven decisions.",
    content: "# Full Guide Content in Markdown\n\n...",
    author: "CRANE JLA Consults",
    category: "Data Analysis",
    readingTime: 14,
    keyTakeaways: ["Identify key metrics", "Choose the right tools", "Visualize your findings"],
    datePublished: "Dec 2025",
    featured: true,
    order: 2,
    tags: ["data", "sme", "profitability"],
  },
];

export const prompts: Prompt[] = [
  {
    id: "prompt_001",
    title: "Literature Review Outliner",
    slug: "literature-review-outliner",
    useCase: "Structure a comprehensive literature review for your research topic with organized sections and key references.",
    promptText: "You are an expert research methodologist. Create a detailed outline for a literature review on the topic of [Your Topic]. The outline should include major sections such as Introduction, Thematic Area 1, Thematic Area 2, Gaps in the Literature, and Conclusion. For each thematic area, suggest 3-5 key concepts or authors to include.",
    category: "Literature Review",
    difficulty: "Beginner",
    dateAdded: "2025-11-26",
    order: 1,
    tags: ["literature", "methodology", "research"],
  },
  {
    id: "prompt_002",
    title: "Research Proposal Evaluator",
    slug: "research-proposal-evaluator",
    useCase: "Get structured feedback on your research proposal to strengthen methodology and clarity.",
    promptText: "Act as a research proposal reviewer for a grant committee. Read the following research proposal and provide structured feedback on its strengths and weaknesses. Focus on the clarity of the research question, the soundness of the methodology, and the feasibility of the project plan. Provide actionable suggestions for improvement.\n\n[Paste Your Research Proposal Here]",
    category: "Research Design",
    difficulty: "Intermediate",
    dateAdded: "2025-11-26",
    order: 2,
    tags: ["proposal", "methodology"],
  },
  {
    id: "prompt_003",
    title: "Data Interpretation Assistant",
    slug: "data-interpretation-assistant",
    useCase: "Generate initial interpretations and insights from a raw dataset summary.",
    promptText: "Below is a summary of statistical analysis from a dataset. Explain the key findings in plain language, identify any potential correlations or significant results, and suggest two possible next steps for deeper analysis.\n\n[Paste your data summary, e.g., mean, median, standard deviation, p-values]",
    category: "Data Analysis",
    difficulty: "Intermediate",
    dateAdded: "2025-11-27",
    order: 3,
    tags: ["data", "analysis", "sme"],
  },
  {
    id: "prompt_004",
    title: "Abstract Generator for Papers",
    slug: "abstract-generator",
    useCase: "Quickly draft a structured abstract for your research paper based on its key sections.",
    promptText: "Generate a 250-word structured abstract for a research paper with the following components:\n\nObjective: [Your research objective]\nMethods: [Your methodology]\nResults: [Your key findings]\nConclusion: [Your main conclusion]\n\nThe abstract should be concise, professional, and suitable for an academic journal.",
    category: "Writing",
    difficulty: "Beginner",
    dateAdded: "2025-11-28",
    order: 4,
    tags: ["writing", "publication", "academic"],
  },
];

export const gems: Gem[] = [
  {
    id: "gem_001",
    title: "Research Proposal Analyzer",
    slug: "research-proposal-analyzer",
    description: "AI-powered analyzer that reviews research proposals for rigor, clarity, and alignment with objectives. Provides structured feedback.",
    geminiLink: "https://gemini.google.com/",
    type: "Analyzer",
    dateCreated: "2025-11-26",
    order: 1,
    tags: ["research", "proposal"],
    featured: true,
  },
  {
    id: "gem_002",
    title: "Academic Paper Generator",
    slug: "academic-paper-generator",
    description: "Generates a draft of an academic paper based on your research notes, data, and outline. Helps overcome writer's block.",
    geminiLink: "https://gemini.google.com/",
    type: "Generator",
    dateCreated: "2025-11-27",
    order: 2,
    tags: ["writing", "academic"],
    featured: true,
  },
  {
    id: "gem_003",
    title: "Qualitative Data Outliner",
    slug: "qualitative-data-outliner",
    description: "Processes interview transcripts or open-ended survey responses to identify key themes and create a thematic outline.",
    geminiLink: "https://gemini.google.com/",
    type: "Outliner",
    dateCreated: "2025-11-28",
    order: 3,
    tags: ["qualitative", "data"],
    featured: true,
  },
];
